version: '3'

services:
    consulserver01:
        image: consul:1.10
        container_name: consulserver01
        hostname: consulserver01
        restart: always
        command: ['agent','-bootstrap-expect=3']
        ports:
           - "8500:8500"
           - "8600:8600/tcp"
           - "8600:8600/udp"
        networks:
            network:
                ipv4_address: 10.5.0.2
    consulserver02:
        image: consul:1.10
        container_name: consulserver02
        hostname: consulserver02
        restart: always
        command: "agent -bootstrap-expect=3"
        ports:
           - "8500:8500"
           - "8600:8600/tcp"
           - "8600:8600/udp"
        networks:
            network:
                ipv4_address: 10.5.0.3
    consulserver03:
        image: consul:1.10
        container_name: consulserver03
        hostname: consulserver03
        restart: always
        command: ['agent','-bootstrap-expect=3']
        ports:
           - "8500:8500"
           - "8600:8600/tcp"
           - "8600:8600/udp"
        networks:
            network:
                ipv4_address: 10.5.0.4
    consulclient01:
        image: consul:1.10
        container_name: consulclient01
        hostname: consultclient01
        command: ['tail','-f','/dev/null']
        volumes:
            - ./clients/consul01:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.5
    consulclient02:
        image: consul:1.10
        container_name: consulclient02
        hostname: consultclient02
        command: ['tail','-f','/dev/null']
        volumes:
            - ./clients/consul02:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.6
    consulclient03:
        image: consul:1.10
        container_name: consulclient03
        hostname: consultclient03
        command: ['tail','-f','/dev/null']
        volumes:
            - ./clients/consul03:/etc/consul.d
        networks:
            network:
                ipv4_address: 10.5.0.7
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
